##  branchLoc-sulkujen väliin tulee alla olevan rivin mukaiset sijainnit kohassa, pilkulla eroteltuna, samalla tavalla kuin _DEFAULT_ rivillä.
##  branchcode, shelving_location, collection_code, sub_location, item.itemtype, item.notforloan-status

1:  branchLoc()		#REVIEW    #REVIEW
+REVIEW: ref(1)
13: branchLoc()		#t-mono    #zt-monografi
+t-mono: ref(13)
14: branchLoc()		#v-exarb   #v-examensarbete
+v-exarb: ref(14)
15: branchLoc()		#v-hand    #v-handbiblioteket
+v-hand: ref(15)
16: branchLoc()		#v-mono    #v-monografi
+v-mono: ref(16)
17: branchLoc()		#v-inst    #v-institutionsexemplar
+v-inst: ref(17)
18: branchLoc()		#v-lager   #v-lager
+v-lager: ref(18)
19: branchLoc()		#v-ref     #v-referens
+v-ref: ref(19)
20: branchLoc()		#v-av      #v-AV-material
+v-av: ref(20)
25: branchLoc()		#T-LANEDISK#zt-lånedisk
+T-LANEDISK: ref(25)
24: branchLoc()		#H-LANEDISK#zh-lånedisk
+H-LANEDISK: ref(24)
26: branchLoc()		#V-KATAL   #v-katalogisering
+V-KATAL: ref(26)
27: branchLoc()		#V-LANEDISK#Lånedisken
+V-LANEDISK: ref(27)
28: branchLoc()		#SELF      #låneautomaten
+SELF: ref(28)
29: branchLoc()		#v-kurs    #v-kursbok
+v-kurs: ref(29)
34: branchLoc()		#MAKSU     #Verkkomaksaminen
+MAKSU: ref(34)
31: branchLoc()		#v-ebok    #v-elektronisk bok
+v-ebok: ref(31)
30: branchLoc()		#v-video   #v-video
+v-video: ref(30)
32: branchLoc()		#v-tidskr  #v-tidskrift
+v-tidskr: ref(32)
33: branchLoc()		#v-etidskr #Elektronisk tidskrift
+v-etidskr: ref(33)
35: branchLoc()		#v-databas #v-databas
+v-databas: ref(35)

_DEFAULT_: branchLoc(KONVERSIO, KONVERSIO, KONVERSIO, KONVERSIO) #Oletusarvot / paikkaansa löytämättömät
